#  1a. Numpy exercises

1. Import the numpy package under the name `np`

`hint: import … as`

In [1]:
import numpy as np


2. Create a zero vector of size 10

`hint: np.zeros`



In [2]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3. Create a vector with values ranging from 0 to 100

`hint: arange`

In [3]:
np.arange(0, 100, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

4. Create a 10x10 matrix with random values and find the minimum, maximum, and mean values. Normalize the said matrix

`hint: min, max, ...`

In [34]:
random_matrix = np.random.rand(10, 10)
min_matrix = np.min(random_matrix)
max_matrix = np.max(random_matrix)
mean_matrix = np.mean(random_matrix)

norm_matrix = (random_matrix - min_matrix) / (max_matrix - min_matrix)

print("Min Value:", min_matrix)
print("Max Value:", max_matrix)
print("Mean Value:", mean_matrix)
print("Normalized Matrix:", norm_matrix)

Min Value: 0.0073486263446203015
Max Value: 0.9972301569721512
Mean Value: 0.4993069181464229
Normalized Matrix: [[0.65926473 0.16762072 0.61030624 0.3613985  0.65141036 0.60150931
  0.41497847 0.35477563 0.49936657 0.97948048]
 [0.59730715 0.66107712 0.55199453 0.92555796 0.20363273 0.00105751
  0.08238863 0.8663937  0.3446192  0.89669958]
 [0.31085193 0.80703616 0.93483548 0.82623937 0.52826657 0.
  0.66484261 1.         0.48181749 0.5539597 ]
 [0.64950268 0.45543711 0.21936442 0.90033637 0.80080425 0.67054438
  0.05895431 0.27932522 0.6982106  0.79375622]
 [0.37729176 0.08904699 0.05313098 0.64204253 0.26796469 0.13566891
  0.70331704 0.41345616 0.21959478 0.11835661]
 [0.3522656  0.33718311 0.95891407 0.94194405 0.11623192 0.11844128
  0.18561504 0.29154768 0.70821693 0.63242699]
 [0.48083536 0.89476509 0.44887964 0.38073577 0.40002925 0.82857221
  0.51618114 0.35862059 0.47207106 0.77457528]
 [0.20517362 0.38952793 0.70703706 0.50360902 0.17532833 0.39400941
  0.41077483 0.0350638

5. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

`hint: np.sqrt, np.arctan2`

In [39]:
# (rows, columns)
cartesian_matrix = np.random.rand(10, 2)

#source: https://www.w3resource.com/python-exercises/numpy/python-numpy-random-exercise-14.php
# extract x y from the cartesian matrix
x, y = cartesian_matrix[:, 0], cartesian_matrix[:, 1]

# Calculating the Euclidean distance (r) using the formula sqrt(x^2 + y^2)
r = np.sqrt(x**2 + y**2)

# Calculating the angles (t) using arctan2() function, which returns the arctangent of y/x in radians
t = np.arctan2(y, x)

for i in range(10):
    print(f"Point {i+1}: x={x[i]:.3f}, y={y[i]:.3f} -> r={r[i]:.3f}, θ={t[i]:.3f} rad")


Point 1: x=0.781, y=0.444 -> r=0.899, θ=0.517 rad
Point 2: x=0.426, y=0.219 -> r=0.479, θ=0.476 rad
Point 3: x=0.624, y=0.898 -> r=1.094, θ=0.963 rad
Point 4: x=0.551, y=0.383 -> r=0.671, θ=0.608 rad
Point 5: x=0.065, y=0.354 -> r=0.360, θ=1.390 rad
Point 6: x=0.908, y=0.886 -> r=1.269, θ=0.773 rad
Point 7: x=0.872, y=0.331 -> r=0.933, θ=0.363 rad
Point 8: x=0.334, y=0.996 -> r=1.050, θ=1.247 rad
Point 9: x=0.472, y=0.724 -> r=0.864, θ=0.994 rad
Point 10: x=0.393, y=0.353 -> r=0.529, θ=0.732 rad


6. Create random vector of size 10 and replace the maximum value by 0

`hint: argmax`

In [48]:
vector = np.random.rand(10)
print('vector: ', vector)
max_index = np.argmax(vector)
print('vector max value: ', vector[max_index])
print('replacing with 0...')
vector[max_index] = 0
print('completed: ', vector)

vector:  [0.96482559 0.08551342 0.12209773 0.86215937 0.7292159  0.24528041
 0.04188299 0.35988241 0.97022365 0.85544136]
vector max value:  0.9702236523594185
replacing with 0...
completed:  [0.96482559 0.08551342 0.12209773 0.86215937 0.7292159  0.24528041
 0.04188299 0.35988241 0.         0.85544136]


7. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

`hint: np.meshgrid`

In [62]:
x = np.arange(0, 1.1, 0.1)
print(x)

X, Y = np.meshgrid(x, x)

# from here i used chatgpt
points = np.zeros(X.shape, dtype=[('x', float), ('y', float)])
points['x'] = X
points['y'] = Y

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


8. Having a scalar `x` and a random vector `v`, find a value in `v` that is closest to `x`

`hint: argmin`

In [73]:
size = 5
v = np.random.rand(size)
print('v = ', v)
x = 2
print('x = ', x)
# create a vector from v, where we subtract x from it and takes the absolute value
# that way, the value closest to 0 will be the one np.argmin finds
v_difference = np.abs(v - x)
min_value = v[np.argmin(v_difference)]
print('Closest to x: ', min_value)

v =  [0.83070452 0.09989808 0.90678095 0.63113013 0.75866482]
x =  2
Closest to x:  0.9067809472756394


9. Consider a random vector with shape (100,2) representing coordinates, find point by point distances and put them in a (100,100) array.

In [146]:
V = np.random.rand(100, 2)
A = V.reshape(100, 1, 2)
B = V.reshape(1, 100, 2)

diff = A - B
euclidean_dist = np.linalg.norm(diff, axis=2)
print("Distance matrix shape:", euclidean_dist)

Distance matrix shape: [[0.         0.4458277  0.80271269 ... 0.89169192 0.85635222 0.44509469]
 [0.4458277  0.         1.12799359 ... 0.86222286 0.86548223 0.88876361]
 [0.80271269 1.12799359 0.         ... 0.78911607 0.71225123 0.58196462]
 ...
 [0.89169192 0.86222286 0.78911607 ... 0.         0.07705443 1.06595839]
 [0.85635222 0.86548223 0.71225123 ... 0.07705443 0.         1.00483363]
 [0.44509469 0.88876361 0.58196462 ... 1.06595839 1.00483363 0.        ]]


10. Create a random (100, 100) matrix with values from 0 to 1. Turn all values lower than 0.5 into 0.0

In [92]:
matrix = np.random.rand(100, 100)
matrix[matrix < 0.5] = 0.0

11. Do a dot product of two matrices and print only the diagonal values.

In [154]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = np.dot(A, B)
print(np.diag(C))

[0.49746508 0.53168172 0.29962227]


12. Swap two rows of a matrix.

In [163]:
A = np.random.rand(2, 2)
print(A)
#[r,c]

A[[0, 1]] = A[[1, 0]]
print('\n<-SWAP->\n')
print(A)


[[0.51933658 0.81402173]
 [0.87314595 0.44014224]]

<-SWAP->

[[0.87314595 0.44014224]
 [0.51933658 0.81402173]]


13. Solve the system of equations:

  $3x - 11y = 3$

  $x - 4y = 6$

  using `numpy.linalg.solve`

In [117]:
A = np.array([[3, -11],
              [1, -4]]) # coefficents of first and second eq.

b = np.array([3, 6]) # y

np.linalg.solve(A, b)

array([-54., -15.])